# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a76bbebf2072739a63516ff653194d45e9ca2ee43014c90a9c6148e570d6461a104d9be41f2ad55b83c7bf40ba04b0e40f05aaeb9555b8628be35f28fa725158

test:
  secret_key_base: 3d56a43b6e88979ed99927a73b42485c16d01ea80cf50a0b1b987d3cf51a6e7e0e1b25050eec9136ee7a551c2efd3cd38c9998ec76808cd10b453923cd9c5691

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
